-- 샘플 배송 데이터 2개 삽입

-- 배송 1: 3인용 소파 세트
INSERT INTO deliveries (
    tracking_number,
    request_type,
    status,
    construction_type,
    shipment_type,
    visit_date,
    visit_time,
    assigned_driver,
    furniture_company,
    main_memo,
    emergency_contact,
    customer_name,
    customer_phone,
    customer_address,
    building_type,
    floor_count,
    elevator_available,
    ladder_truck,
    disposal,
    room_movement,
    wall_construction,
    product_name,
    furniture_product_code,
    product_weight,
    product_size,
    box_size,
    furniture_requests,
    driver_notes,
    installation_photos
) VALUES (
    'MK202401001',
    '일반',
    'pending',
    '조립설치',
    '직배송',
    '2024-01-17',
    '14:00-18:00',
    '김기사',
    '한샘가구',
    '신속 배송 요청',
    '010-9999-8888',
    '이영희',
    '010-1234-5678',
    '부산시 해운대구 마린시티 456',
    '아파트',
    '15층',
    '있음',
    '불필요',
    '없음',
    '있음',
    '필요',
    '3인용 소파 세트',
    'HSM-SF-001',
    '45kg',
    '220 x 90 x 80cm',
    '230 x 100 x 90cm',
    '소파 배치 시 TV 보는 각도 고려 부탁드립니다.',
    '엘리베이터 사용 가능, 고객 매우 친절함',
    JSON_ARRAY(
        'https://picsum.photos/300/300?random=1',
        'https://picsum.photos/300/300?random=2',
        'https://picsum.photos/300/300?random=3',
        'https://picsum.photos/300/300?random=4'
    )
);

-- 배송 2: 냉장고 (4도어)
INSERT INTO deliveries (
    tracking_number,
    request_type,
    status,
    construction_type,
    shipment_type,
    visit_date,
    visit_time,
    assigned_driver,
    furniture_company,
    main_memo,
    emergency_contact,
    customer_name,
    customer_phone,
    customer_address,
    building_type,
    floor_count,
    elevator_available,
    ladder_truck,
    disposal,
    room_movement,
    wall_construction,
    product_name,
    furniture_product_code,
    product_weight,
    product_size,
    box_size,
    furniture_requests,
    driver_notes,
    installation_photos
) VALUES (
    'MK202401002',
    '쿠방',
    'in_transit',
    '단순배송',
    '물류센터경유',
    '2024-01-16',
    '09:00-12:00',
    '이기사',
    '이케아',
    '냉장상품 - 온도관리 주의',
    '010-8888-7777',
    '최지훈',
    '010-9876-5432',
    '대구시 수성구 동대구로 321',
    '빌라',
    '5층',
    '없음',
    '필요',
    '있음',
    '있음',
    '불필요',
    '냉장고 (4도어)',
    'IKEA-RF-402',
    '85kg',
    '180 x 60 x 70cm',
    '190 x 70 x 80cm',
    '냉장고 설치 후 전원 연결 및 동작 테스트 필수',
    '5층 엘리베이터 없음, 사다리차 이용함',
    JSON_ARRAY(
        'https://picsum.photos/300/300?random=5',
        'https://picsum.photos/300/300?random=6'
    )
);

-- 배송 상세 정보 1
INSERT INTO delivery_details (
    delivery_id,
    delivery_fee,
    special_instructions,
    delivery_time_preference,
    fragile,
    insurance_value,
    cod_amount,
    driver_id,
    driver_name,
    estimated_delivery,
    actual_delivery,
    delivery_attempts,
    last_location,
    notes
) VALUES (
    1,
    3500.00,
    '문앞 배송 요청',
    '오후 2-6시',
    FALSE,
    50000.00,
    0.00,
    NULL,
    NULL,
    '2024-01-17 15:00:00',
    NULL,
    0,
    '물류센터',
    '신속 배송 요청'
);

-- 배송 상세 정보 2
INSERT INTO delivery_details (
    delivery_id,
    delivery_fee,
    special_instructions,
    delivery_time_preference,
    fragile,
    insurance_value,
    cod_amount,
    driver_id,
    driver_name,
    estimated_delivery,
    actual_delivery,
    delivery_attempts,
    last_location,
    notes
) VALUES (
    2,
    5500.00,
    '냉장 보관 필수',
    '오전 중',
    TRUE,
    100000.00,
    85000.00,
    'D001',
    '김배송',
    '2024-01-16 11:00:00',
    NULL,
    1,
    '대구 물류센터',
    '냉장상품 - 온도관리 주의'
);